name: RunFatGirl
favicon: null
layout_spectrum: 0.63472
typography_spectrum: 0.12036
title: Fat Girls Run Too
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff9e9'
    - '#f9789f'
    - '#ada6ad'
    - '#756f79'
    - '#373a4d'
  brandStrength: 0.5625
  lightness: 0.23287371918559074
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
