name: RunFatGirl
favicon: null
layout_spectrum: 0.9131091297604144
typography_spectrum: 0.365986610064283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8447066633962095
  lightness: 0.23287371918559074
  saturation: 0.36634306190535426
  rhythmicContrast: 0.06798408948816359
purpose: []
